<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEhMtKfx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEhMtKfx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEhMtKfx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEhMtKfx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEhMtKfx\App_KernelDevDebugContainer([
    'container.build_hash' => 'EhMtKfx',
    'container.build_id' => '87e84293',
    'container.build_time' => 1677187729,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEhMtKfx');
