<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXC2Nmui\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXC2Nmui/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXC2Nmui.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXC2Nmui\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXC2Nmui\App_KernelDevDebugContainer([
    'container.build_hash' => 'XC2Nmui',
    'container.build_id' => 'd69a278a',
    'container.build_time' => 1678405185,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXC2Nmui');
