<?php

namespace ContainerKQoCclH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UvgQuService extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator._UvgQu_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._UvgQu_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categoria' => ['privates', '.errored..service_locator._UvgQu_.App\\Entity\\Categoria', NULL, 'Cannot autowire service ".service_locator._UvgQu_": it references class "App\\Entity\\Categoria" but no such service exists.'],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'categoria' => 'App\\Entity\\Categoria',
            'paginator' => '?',
        ]);
    }
}
