<?php

namespace ContainerKQoCclH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Xkft7B4Service extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.service_locator.Xkft7B4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Xkft7B4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'almacen' => ['privates', '.errored..service_locator.Xkft7B4.App\\Entity\\Almacen', NULL, 'Cannot autowire service ".service_locator.Xkft7B4": it references class "App\\Entity\\Almacen" but no such service exists.'],
            'asignacion' => ['privates', '.errored..service_locator.Xkft7B4.App\\Entity\\Asignacion', NULL, 'Cannot autowire service ".service_locator.Xkft7B4": it references class "App\\Entity\\Asignacion" but no such service exists.'],
            'usuario' => ['privates', '.errored..service_locator.Xkft7B4.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.Xkft7B4": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'almacen' => 'App\\Entity\\Almacen',
            'asignacion' => 'App\\Entity\\Asignacion',
            'usuario' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
        ]);
    }
}
