<?php

namespace ContainerKQoCclH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAsignacion2Service extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Xkft7B4.App\Entity\Asignacion' shared service.
     *
     * @return \App\Entity\Asignacion
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Xkft7B4": it references class "App\\Entity\\Asignacion" but no such service exists.');
    }
}
