<?php

namespace ContainerKQoCclH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlmacenProducto2Service extends App_KernelEnvDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.xxiqoLO.App\Entity\AlmacenProducto' shared service.
     *
     * @return \App\Entity\AlmacenProducto
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.xxiqoLO": it references class "App\\Entity\\AlmacenProducto" but no such service exists.');
    }
}
