<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUDXbRwe\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUDXbRwe/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerUDXbRwe.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerUDXbRwe\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerUDXbRwe\App_KernelProdContainer([
    'container.build_hash' => 'UDXbRwe',
    'container.build_id' => '2f788e85',
    'container.build_time' => 1654006480,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUDXbRwe');
