<?php

namespace ContainerLawXzQA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XUL7GfWService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.xUL7GfW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xUL7GfW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'almacen' => ['privates', '.errored..service_locator.xUL7GfW.App\\Entity\\Almacen', NULL, 'Cannot autowire service ".service_locator.xUL7GfW": it references class "App\\Entity\\Almacen" but no such service exists.'],
            'traslado' => ['privates', '.errored..service_locator.xUL7GfW.App\\Entity\\Traslado', NULL, 'Cannot autowire service ".service_locator.xUL7GfW": it references class "App\\Entity\\Traslado" but no such service exists.'],
            'trasladoLote' => ['privates', '.errored..service_locator.xUL7GfW.App\\Entity\\TrasladoLote', NULL, 'Cannot autowire service ".service_locator.xUL7GfW": it references class "App\\Entity\\TrasladoLote" but no such service exists.'],
            'usuario' => ['privates', '.errored..service_locator.xUL7GfW.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.xUL7GfW": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'almacen' => 'App\\Entity\\Almacen',
            'traslado' => 'App\\Entity\\Traslado',
            'trasladoLote' => 'App\\Entity\\TrasladoLote',
            'usuario' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
        ]);
    }
}
