<?php

namespace ContainerLawXzQA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAsignacionService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.0jyU7Ie.App\Entity\Asignacion' shared service.
     *
     * @return \App\Entity\Asignacion
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.0jyU7Ie": it references class "App\\Entity\\Asignacion" but no such service exists.');
    }
}
