<?php

namespace ContainerLawXzQA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlmacen6Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.NjpkX28.App\Entity\Almacen' shared service.
     *
     * @return \App\Entity\Almacen
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.NjpkX28": it references class "App\\Entity\\Almacen" but no such service exists.');
    }
}
