<?php

namespace ContainerLawXzQA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoria2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.NS_IKj0.App\Entity\Categoria' shared service.
     *
     * @return \App\Entity\Categoria
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.NS_IKj0": it references class "App\\Entity\\Categoria" but no such service exists.');
    }
}
