<?php

namespace ContainerLawXzQA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGedmo_Listener_SoftdeleteableService extends App_KernelProdContainer
{
    /*
     * Gets the private 'gedmo.listener.softdeleteable' shared service.
     *
     * @return \Gedmo\SoftDeleteable\SoftDeleteableListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['gedmo.listener.softdeleteable'] = $instance = new \Gedmo\SoftDeleteable\SoftDeleteableListener();

        $instance->setAnnotationReader(($container->privates['annotations.cached_reader'] ?? $container->getAnnotations_CachedReaderService()));

        return $instance;
    }
}
