<?php

namespace ContainerLawXzQA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportacion2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.OtNWNhu.App\Entity\Importacion' shared service.
     *
     * @return \App\Entity\Importacion
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.OtNWNhu": it references class "App\\Entity\\Importacion" but no such service exists.');
    }
}
