<?php

namespace ContainerLawXzQA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoteService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.xxiqoLO.App\Entity\Lote' shared service.
     *
     * @return \App\Entity\Lote
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.xxiqoLO": it references class "App\\Entity\\Lote" but no such service exists.');
    }
}
