<?php

namespace ContainerOkIQS9a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__KiHaloService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator..kiHalo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..kiHalo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categoria' => ['privates', '.errored..service_locator..kiHalo.App\\Entity\\Categoria', NULL, 'Cannot autowire service ".service_locator..kiHalo": it references class "App\\Entity\\Categoria" but no such service exists.'],
            'subcategoria' => ['privates', '.errored..service_locator..kiHalo.App\\Entity\\Subcategoria', NULL, 'Cannot autowire service ".service_locator..kiHalo": it references class "App\\Entity\\Subcategoria" but no such service exists.'],
        ], [
            'categoria' => 'App\\Entity\\Categoria',
            'subcategoria' => 'App\\Entity\\Subcategoria',
        ]);
    }
}
