<?php

namespace ContainerOkIQS9a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAsignacionLoteService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.0jyU7Ie.App\Entity\AsignacionLote' shared service.
     *
     * @return \App\Entity\AsignacionLote
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.0jyU7Ie": it references class "App\\Entity\\AsignacionLote" but no such service exists.');
    }
}
