<?php

namespace ContainerOkIQS9a;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_AccessMapService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.access_map' shared service.
     *
     * @return \Symfony\Component\Security\Http\AccessMap
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['security.access_map'] = $instance = new \Symfony\Component\Security\Http\AccessMap();

        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/iniciar-sesion'), [0 => 'PUBLIC_ACCESS'], 'https');
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/sesion-cerrada'), [0 => 'PUBLIC_ACCESS'], 'https');
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/administracion'), [0 => 'ROLE_ADMINISTRADOR'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/inventario'), [0 => 'ROLE_GESTOR'], NULL);
        $instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/'), [0 => 'IS_AUTHENTICATED_FULLY'], NULL);

        return $instance;
    }
}
