<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKQoCclH\App_KernelEnvDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKQoCclH/App_KernelEnvDebugContainer.php') {
    touch(__DIR__.'/ContainerKQoCclH.legacy');

    return;
}

if (!\class_exists(App_KernelEnvDebugContainer::class, false)) {
    \class_alias(\ContainerKQoCclH\App_KernelEnvDebugContainer::class, App_KernelEnvDebugContainer::class, false);
}

return new \ContainerKQoCclH\App_KernelEnvDebugContainer([
    'container.build_hash' => 'KQoCclH',
    'container.build_id' => 'f89387bb',
    'container.build_time' => 1677187713,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKQoCclH');
