<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Producto extends \App\Entity\Producto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'codigo', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'referencia', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'codigoBarra', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'precio', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'cantidad', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'descripcion', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'foto', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'categoria', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'subcategoria', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'usuarioCreado', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'fechaCreado', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'almacenes'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'codigo', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'referencia', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'codigoBarra', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'nombre', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'precio', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'cantidad', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'descripcion', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'foto', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'categoria', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'subcategoria', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'usuarioCreado', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'fechaCreado', '' . "\0" . 'App\\Entity\\Producto' . "\0" . 'almacenes'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Producto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigo', []);

        return parent::getCodigo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigo(?string $codigo): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigo', [$codigo]);

        return parent::setCodigo($codigo);
    }

    /**
     * {@inheritDoc}
     */
    public function getReferencia(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferencia', []);

        return parent::getReferencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferencia(?string $referencia): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferencia', [$referencia]);

        return parent::setReferencia($referencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoBarra(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoBarra', []);

        return parent::getCodigoBarra();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigoBarra(?string $codigoBarra): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigoBarra', [$codigoBarra]);

        return parent::setCodigoBarra($codigoBarra);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre(?string $nombre): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecio(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecio', []);

        return parent::getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecio(?float $precio): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecio', [$precio]);

        return parent::setPrecio($precio);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', []);

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion(?string $descripcion): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', [$descripcion]);

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreado(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreado', []);

        return parent::getFechaCreado();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreado(?\DateTimeInterface $fechaCreado): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreado', [$fechaCreado]);

        return parent::setFechaCreado($fechaCreado);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoria(): ?\App\Entity\Categoria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoria', []);

        return parent::getCategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoria(?\App\Entity\Categoria $categoria): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoria', [$categoria]);

        return parent::setCategoria($categoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioCreado(): ?\App\Entity\Usuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioCreado', []);

        return parent::getUsuarioCreado();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioCreado(?\App\Entity\Usuario $usuarioCreado): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioCreado', [$usuarioCreado]);

        return parent::setUsuarioCreado($usuarioCreado);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlmacenes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlmacenes', []);

        return parent::getAlmacenes();
    }

    /**
     * {@inheritDoc}
     */
    public function addAlmacene(\App\Entity\AlmacenProducto $almacene): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAlmacene', [$almacene]);

        return parent::addAlmacene($almacene);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAlmacene(\App\Entity\AlmacenProducto $almacene): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAlmacene', [$almacene]);

        return parent::removeAlmacene($almacene);
    }

    /**
     * {@inheritDoc}
     */
    public function getFoto(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFoto', []);

        return parent::getFoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setFoto(?string $foto): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFoto', [$foto]);

        return parent::setFoto($foto);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidad(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidad', []);

        return parent::getCantidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidad(?int $cantidad): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidad', [$cantidad]);

        return parent::setCantidad($cantidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubcategoria(): ?\App\Entity\Subcategoria
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubcategoria', []);

        return parent::getSubcategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubcategoria(?\App\Entity\Subcategoria $subcategoria): \App\Entity\Producto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubcategoria', [$subcategoria]);

        return parent::setSubcategoria($subcategoria);
    }

}
