<?php

namespace ContainerHf6At7N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N26dx4XService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.n26dx4X' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.n26dx4X'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'usuario' => ['privates', '.errored..service_locator.n26dx4X.App\\Entity\\Usuario', NULL, 'Cannot autowire service ".service_locator.n26dx4X": it references class "App\\Entity\\Usuario" but no such service exists.'],
            'usuarioRepository' => ['privates', 'App\\Repository\\UsuarioRepository', 'getUsuarioRepositoryService', true],
        ], [
            'usuario' => 'App\\Entity\\Usuario',
            'usuarioRepository' => 'App\\Repository\\UsuarioRepository',
        ]);
    }
}
