<?php

namespace ContainerHf6At7N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_BOjGlk6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.bOjGlk6' shared service.
     *
     * @return \Knp\Snnapy\Pdf
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\PDFController::index()": the $pdf argument is type-hinted with the non-existent class or interface: "Knp\\Snnapy\\Pdf".');
    }
}
