<?php

namespace ContainerHf6At7N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlmacen4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.BnPByhX.App\Entity\Almacen' shared service.
     *
     * @return \App\Entity\Almacen
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.BnPByhX": it references class "App\\Entity\\Almacen" but no such service exists.');
    }
}
