<?php

namespace ContainerScqAvDQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KDSNa6QService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KDSNa6Q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KDSNa6Q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'userRepository' => ['privates', 'App\\Repository\\UsuarioRepository', 'getUsuarioRepositoryService', true],
            'usuario' => ['privates', '.errored..service_locator.KDSNa6Q.App\\Entity\\Usuario', NULL, 'Cannot autowire service ".service_locator.KDSNa6Q": it references class "App\\Entity\\Usuario" but no such service exists.'],
        ], [
            'userRepository' => 'App\\Repository\\UsuarioRepository',
            'usuario' => 'App\\Entity\\Usuario',
        ]);
    }
}
