<?php

namespace ContainerScqAvDQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XxiqoLOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xxiqoLO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xxiqoLO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'almacen' => ['privates', '.errored..service_locator.xxiqoLO.App\\Entity\\Almacen', NULL, 'Cannot autowire service ".service_locator.xxiqoLO": it references class "App\\Entity\\Almacen" but no such service exists.'],
            'almacenProducto' => ['privates', '.errored..service_locator.xxiqoLO.App\\Entity\\AlmacenProducto', NULL, 'Cannot autowire service ".service_locator.xxiqoLO": it references class "App\\Entity\\AlmacenProducto" but no such service exists.'],
            'lote' => ['privates', '.errored..service_locator.xxiqoLO.App\\Entity\\Lote', NULL, 'Cannot autowire service ".service_locator.xxiqoLO": it references class "App\\Entity\\Lote" but no such service exists.'],
            'usuario' => ['privates', '.errored..service_locator.xxiqoLO.Symfony\\Component\\Security\\Core\\User\\UserInterface', NULL, 'Cannot autowire service ".service_locator.xxiqoLO": it references interface "Symfony\\Component\\Security\\Core\\User\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'almacen' => 'App\\Entity\\Almacen',
            'almacenProducto' => 'App\\Entity\\AlmacenProducto',
            'lote' => 'App\\Entity\\Lote',
            'usuario' => 'Symfony\\Component\\Security\\Core\\User\\UserInterface',
        ]);
    }
}
