<?php

namespace ContainerScqAvDQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImportacionLoteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0s.jFW9.App\Entity\ImportacionLote' shared service.
     *
     * @return \App\Entity\ImportacionLote
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.0s.jFW9": it references class "App\\Entity\\ImportacionLote" but no such service exists.');
    }
}
