<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9x3QeSG\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9x3QeSG/App_KernelProdContainer.php') {
    touch(__DIR__.'/Container9x3QeSG.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\Container9x3QeSG\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \Container9x3QeSG\App_KernelProdContainer([
    'container.build_hash' => '9x3QeSG',
    'container.build_id' => 'b108d225',
    'container.build_time' => 1677180896,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9x3QeSG');
