<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLawXzQA\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLawXzQA/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerLawXzQA.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerLawXzQA\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerLawXzQA\App_KernelProdContainer([
    'container.build_hash' => 'LawXzQA',
    'container.build_id' => '1b9f75c5',
    'container.build_time' => 1677184326,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLawXzQA');
