<?php

namespace Container96j5L06;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoggableListenerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'Gedmo\Loggable\LoggableListener' shared service.
     *
     * @return \Gedmo\Loggable\LoggableListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/event-manager/lib/Doctrine/Common/EventSubscriber.php';
        include_once \dirname(__DIR__, 4).'/vendor/gedmo/doctrine-extensions/src/Mapping/MappedEventSubscriber.php';
        include_once \dirname(__DIR__, 4).'/vendor/gedmo/doctrine-extensions/src/Loggable/LoggableListener.php';

        $container->privates['Gedmo\\Loggable\\LoggableListener'] = $instance = new \Gedmo\Loggable\LoggableListener();

        $instance->setAnnotationReader(($container->privates['annotations.cached_reader'] ?? $container->getAnnotations_CachedReaderService()));

        return $instance;
    }
}
