<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Asignacion extends \App\Entity\Asignacion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Asignacion' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Asignacion' . "\0" . 'almacen', '' . "\0" . 'App\\Entity\\Asignacion' . "\0" . 'areaServicio', '' . "\0" . 'App\\Entity\\Asignacion' . "\0" . 'terceros', '' . "\0" . 'App\\Entity\\Asignacion' . "\0" . 'encargado', '' . "\0" . 'App\\Entity\\Asignacion' . "\0" . 'fecha', '' . "\0" . 'App\\Entity\\Asignacion' . "\0" . 'ordenTrabajo', '' . "\0" . 'App\\Entity\\Asignacion' . "\0" . 'observaciones', '' . "\0" . 'App\\Entity\\Asignacion' . "\0" . 'usuarioCreado', '' . "\0" . 'App\\Entity\\Asignacion' . "\0" . 'fechaCreado', '' . "\0" . 'App\\Entity\\Asignacion' . "\0" . 'lotes'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Asignacion' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Asignacion' . "\0" . 'almacen', '' . "\0" . 'App\\Entity\\Asignacion' . "\0" . 'areaServicio', '' . "\0" . 'App\\Entity\\Asignacion' . "\0" . 'terceros', '' . "\0" . 'App\\Entity\\Asignacion' . "\0" . 'encargado', '' . "\0" . 'App\\Entity\\Asignacion' . "\0" . 'fecha', '' . "\0" . 'App\\Entity\\Asignacion' . "\0" . 'ordenTrabajo', '' . "\0" . 'App\\Entity\\Asignacion' . "\0" . 'observaciones', '' . "\0" . 'App\\Entity\\Asignacion' . "\0" . 'usuarioCreado', '' . "\0" . 'App\\Entity\\Asignacion' . "\0" . 'fechaCreado', '' . "\0" . 'App\\Entity\\Asignacion' . "\0" . 'lotes'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Asignacion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTerceros(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTerceros', []);

        return parent::getTerceros();
    }

    /**
     * {@inheritDoc}
     */
    public function setTerceros(?string $terceros): \App\Entity\Asignacion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTerceros', [$terceros]);

        return parent::setTerceros($terceros);
    }

    /**
     * {@inheritDoc}
     */
    public function getEncargado(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEncargado', []);

        return parent::getEncargado();
    }

    /**
     * {@inheritDoc}
     */
    public function setEncargado(?string $encargado): \App\Entity\Asignacion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEncargado', [$encargado]);

        return parent::setEncargado($encargado);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha(?\DateTimeInterface $fecha): \App\Entity\Asignacion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdenTrabajo(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdenTrabajo', []);

        return parent::getOrdenTrabajo();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrdenTrabajo(?string $ordenTrabajo): \App\Entity\Asignacion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrdenTrabajo', [$ordenTrabajo]);

        return parent::setOrdenTrabajo($ordenTrabajo);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservaciones(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservaciones', []);

        return parent::getObservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservaciones(?string $observaciones): \App\Entity\Asignacion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservaciones', [$observaciones]);

        return parent::setObservaciones($observaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreado(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreado', []);

        return parent::getFechaCreado();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreado(?\DateTimeInterface $fechaCreado): \App\Entity\Asignacion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreado', [$fechaCreado]);

        return parent::setFechaCreado($fechaCreado);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlmacen(): ?\App\Entity\Almacen
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlmacen', []);

        return parent::getAlmacen();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlmacen(?\App\Entity\Almacen $almacen): \App\Entity\Asignacion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlmacen', [$almacen]);

        return parent::setAlmacen($almacen);
    }

    /**
     * {@inheritDoc}
     */
    public function getAreaServicio(): ?\App\Entity\AreaServicio
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAreaServicio', []);

        return parent::getAreaServicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setAreaServicio(?\App\Entity\AreaServicio $areaServicio): \App\Entity\Asignacion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAreaServicio', [$areaServicio]);

        return parent::setAreaServicio($areaServicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioCreado(): ?\App\Entity\Usuario
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioCreado', []);

        return parent::getUsuarioCreado();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioCreado(?\App\Entity\Usuario $usuarioCreado): \App\Entity\Asignacion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioCreado', [$usuarioCreado]);

        return parent::setUsuarioCreado($usuarioCreado);
    }

    /**
     * {@inheritDoc}
     */
    public function getLotes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLotes', []);

        return parent::getLotes();
    }

    /**
     * {@inheritDoc}
     */
    public function addLote(\App\Entity\AsignacionLote $lote): \App\Entity\Asignacion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLote', [$lote]);

        return parent::addLote($lote);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLote(\App\Entity\AsignacionLote $lote): \App\Entity\Asignacion
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLote', [$lote]);

        return parent::removeLote($lote);
    }

}
