<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQY8eH5S\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQY8eH5S/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerQY8eH5S.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerQY8eH5S\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerQY8eH5S\App_KernelProdContainer([
    'container.build_hash' => 'QY8eH5S',
    'container.build_id' => '8e9d9b89',
    'container.build_time' => 1654007524,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQY8eH5S');
