security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 
            algorithm: auto
            cost:      15
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\Usuario
                property: username
    firewalls:
        main:
            pattern: ^/
            user_checker: App\Security\UserChecker
            form_login:
                provider: app_user_provider
                login_path: app_login
                check_path: app_login
                default_target_path: app_index
                always_use_default_target_path: true
                enable_csrf: true
                failure_path: app_login
            logout: 
                path: app_logout
                target: app_logout_vista

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/iniciar-sesion, roles: PUBLIC_ACCESS, requires_channel: https }
         - { path: ^/sesion-cerrada, roles: PUBLIC_ACCESS, requires_channel: https }
         - { path: ^/administracion, roles: ROLE_ADMINISTRADOR }
         - { path: ^/inventario, roles: ROLE_GESTOR }
         - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
