<?php

namespace ContainerXC2Nmui;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IKbd0nService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IKbd_0n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IKbd_0n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'encoder' => ['services', '.container.private.security.password_encoder', 'get_Container_Private_Security_PasswordEncoderService', true],
            'usuario' => ['privates', '.errored..service_locator.IKbd_0n.App\\Entity\\Usuario', NULL, 'Cannot autowire service ".service_locator.IKbd_0n": it references class "App\\Entity\\Usuario" but no such service exists.'],
        ], [
            'encoder' => '?',
            'usuario' => 'App\\Entity\\Usuario',
        ]);
    }
}
