<?php

namespace ContainerXC2Nmui;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProveedorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Xi.HRQ7.App\Entity\Proveedor' shared service.
     *
     * @return \App\Entity\Proveedor
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Xi.HRQ7": it references class "App\\Entity\\Proveedor" but no such service exists.');
    }
}
