<?php

namespace ContainerXC2Nmui;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTraslado2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.xUL7GfW.App\Entity\Traslado' shared service.
     *
     * @return \App\Entity\Traslado
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.xUL7GfW": it references class "App\\Entity\\Traslado" but no such service exists.');
    }
}
