<?php

namespace ContainerXC2Nmui;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsuarioService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.IKbd_0n.App\Entity\Usuario' shared service.
     *
     * @return \App\Entity\Usuario
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.IKbd_0n": it references class "App\\Entity\\Usuario" but no such service exists.');
    }
}
