<?php

namespace Container9x3QeSG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGedmo_Listener_TreeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'gedmo.listener.tree' shared service.
     *
     * @return \Gedmo\Tree\TreeListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['gedmo.listener.tree'] = $instance = new \Gedmo\Tree\TreeListener();

        $instance->setAnnotationReader(($container->privates['annotations.cached_reader'] ?? $container->getAnnotations_CachedReaderService()));

        return $instance;
    }
}
