<?php

namespace Container9x3QeSG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSubcategoriaService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator..kiHalo.App\Entity\Subcategoria' shared service.
     *
     * @return \App\Entity\Subcategoria
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator..kiHalo": it references class "App\\Entity\\Subcategoria" but no such service exists.');
    }
}
